// Code generated by mgen.
// DO NOT EDIT

package iface

import (
	"log"

	"gopkg.in/mgo.v2"
)

//go:generate goimports -w model.mg.go
type Database interface {
	InitDB(session *mgo.Session)
}

func Connect(host string, dbs ...Database) {
	session, err := mgo.Dial(host)
	if err != nil {
		log.Fatalf("[FATAL] connect the database failed")
	}

	if len(dbs) == 0 {
		log.Fatalf("[FATAL] your must the select database")
	}

	for _, db := range dbs {
		db.InitDB(session)
	}
}
